### PR TITLE
v2.0.4

### PR DESCRIPTION
**Pull request by BlueSolei**
Hi,
I update `conandata.yml` to emsdk version 2.0.4
Can you merge & build & upload it to bincrafters?

### CODE REVIEW

**Comment by ericLemanissier** [comment]
retrigger CI after base branch modification

**Comment by ericLemanissier** [comment]
linux installer fails with :
```
Running post-install step: npm ci ...
Error running ['/home/conan/.conan/data/emsdk_installer/2.0.4/bincrafters/testing/build/4dad828fb1d296fe71e8fc0664d8940000aed6d8/source_subfolder/node/12.18.1_64bit/bin/npm', 'ci', '--production']:
node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by node)
node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by node)
node: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by node)
node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by node)
node: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by node)
node: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by node)
node: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by node)
```
Do you have an idea ?

**Comment by BlueSolei** [comment]
No, I am not a Linux guy 😔

**Comment by BlueSolei** [comment]
Could be related to https://github.com/emscripten-core/emscripten/issues/6252?

**Comment by ericLemanissier** [comment]
it looks similar yes, maybe you could try the suggestion in https://github.com/emscripten-core/emscripten/issues/6252#issuecomment-557194971 ?

**Pull request closed without merging**
